GestionStages/src/Entity/Stage.php
<?php

namespace App\Entity;

use App\Repository\StageRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity()
 * @ORM\Table(name="Stage")
 * @ORM\HasLifecycleCallbacks()
 * @ORM\Entity(repositoryClass=StageRepository::class)
 */
class Stage
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *     min=5,
     *     max=20,
     *     minMessage="Le poste ne doit pas avoir minimun 5 caractères",
     *     maxMessage="Le poste ne doit pas depasser 20 caratères"
     * )
     */
    private $poste;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(
     *     min=10,
     *     max=255,
     *     minMessage="La description ne doit pas avoir minimun 10 caractères",
     *     maxMessage="Le poste ne doit pas depasser 20 caratères"
     * )
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\Column(type="boolean")
     */
    private $actif;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_creation;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_expiration;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_modification;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="L'e-mail '{{ value }}' n'est pas un e-mail valide")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *     min=3,
     *     max=255,
     *     minMessage="La sociéte ne doit pas avoir minimun 3 caractères",
     *     maxMessage="Le sociéte ne doit pas depasser 15 caratères"
     * )
     */
    private $societe;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *     min=3,
     *     max=255,
     *     minMessage="La ville ne doit pas avoir minimun 3 caractères",
     *     maxMessage="Le ville ne doit pas depasser 15 caratères"
     * )
     */
    private $ville;

    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="stages")
     * @ORM\JoinColumn(nullable=false)
     */
    private $categorie;

    /**
     * @ORM\ManyToMany(targetEntity=Tuteur::class, inversedBy="stages")
     */
    private $tuteurs;

    /**
     * @Gedmo\Slug(fields={"poste"})
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    public function __construct()
    {
        $this->tuteurs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPoste(): ?string
    {
        return $this->poste;
    }

    public function setPoste(string $poste): self
    {
        $this->poste = $poste;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getActif(): ?bool
    {
        return $this->actif;
    }

    public function setActif(bool $actif): self
    {
        $this->actif = $actif;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getDateExpiration(): ?\DateTimeInterface
    {
        return $this->date_expiration;
    }

    public function setDateExpiration(?\DateTimeInterface $date_expiration): self
    {
        $this->date_expiration = $date_expiration;

        return $this;
    }

    public function getDateModification(): ?\DateTimeInterface
    {
        return $this->date_modification;
    }

    public function setDateModification(?\DateTimeInterface $date_modification): self
    {
        $this->date_modification = $date_modification;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getSociete(): ?string
    {
        return $this->societe;
    }

    public function setSociete(string $societe): self
    {
        $this->societe = $societe;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    /**
     * @return Collection|Tuteur[]
     */
    public function getTuteurs(): Collection
    {
        return $this->tuteurs;
    }

    public function addTuteur(Tuteur $tuteur): self
    {
        if (!$this->tuteurs->contains($tuteur)) {
            $this->tuteurs[] = $tuteur;
        }

        return $this;
    }

    public function removeTuteur(Tuteur $tuteur): self
    {
        $this->tuteurs->removeElement($tuteur);

        return $this;
    }


    /**
     * @ORM\PrePersist()
     */
    public function prePersist()
    {
        $this->date_creation = new \DateTime();
        $this->date_modification = new \DateTime();

        if (!$this->date_expiration) {
            $this->date_expiration = (clone $this->date_creation)->modify('+20 days');
        }
    }

    /**
     * @ORM\PreUpdate() */
    public function preUpdate()
    {
        $this->date_modification = new \DateTime();
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function __toString(){
        return $this->poste;
    }

}

GestionStages/src/Form/StageType.php
<?php

namespace App\Form;

use App\Entity\Categorie;
use App\Entity\Stage;
use App\Entity\Tuteur;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class StageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('poste', TextType::class)
            ->add('type',ChoiceType::class, [
                'choices' => [ 'Oui' => true,'Non' => false,],
                'label' => 'Plein temps ?'])
            ->add('description', TextareaType::class)
            ->add('actif',ChoiceType::class, [
                'choices' => [
                    'Oui' => true,'Non' => false, ], 'label' => 'Actif ?'])
            ->add('email', EmailType::class)
            ->add('societe', TextType::class)
            ->add('ville', TextType::class)
            ->add('categorie', EntityType::class, [
                'class' => Categorie::class, 'choice_label' => 'nom',])
            ->add('tuteurs', EntityType::class, [
                'class' => Tuteur::class, 'multiple' => true, 'expanded' => true, 'choice_label' => 'nom',
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Stage::class,
        ]);
    }
}

GestionStages/src/Controller/StageController.php
<?php

namespace App\Controller;

use App\Entity\Stage;
use App\Form\StageType;
use App\Service\StageHistoryService;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Require ROLE_USER for *every* controller method in this class.
 *
 * @IsGranted("ROLE_USER")
 *
 * @Route("/{_locale}/")
 */


class StageController extends AbstractController
{
    /**
     * Lister tous les stages.
     * @Route("/stage/", name="stage.list")
     * @param EntityManagerInterface $em
     * @param StageHistoryService $stageHistoryService
     * @return Response
     */
    public function list(EntityManagerInterface $em, StageHistoryService $stageHistoryService) : Response
    {
        $stages = $this->getDoctrine()->getRepository(Stage::class)->getStagesNonExpires();

        /*$query = $em->createQuery(
            'SELECT s FROM App:Stage s WHERE s.date_expiration > :date'
        )->setParameter('date', new \DateTime()); $stages = $query->getResult();
        $stages = $query->getResult();*/

        return $this->render('stage/list.html.twig', [
            'stages' => $stages,
            'historyStages' => $stageHistoryService->getStages(),
            ]);
    }

    /**
     * Chercher et afficher un stage.
     * @Route("/stage/{slug}", name="stage.show")
     * @param Stage $stage
     * @param StageHistoryService $stageHistoryService
     * @return Response
     */
    public function show(Stage $stage, StageHistoryService $stageHistoryService) : Response
    {
        $stageHistoryService->addStage($stage);

        return $this->render('stage/show.html.twig', [
            'stage' => $stage, ]);
    }

    /**
     * Créer un nouveau stage.
     * @Route("/nouveau-stage", name="stage.create") * @param Request $request
     * @param Request $request
     * @param EntityManagerInterface $em
     * @return RedirectResponse|Response
     */
    public function create(Request $request, EntityManagerInterface $em) : Response
    {
        $stage = new Stage();

        $form = $this->createForm(StageType::class, $stage);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($stage);
            $em->flush();
            return $this->redirectToRoute('stage.list');
        }
        return $this->render('stage/create.html.twig', [
            'form' => $form->createView(),
            'editMode' => $stage->getId() !== null,
            ]);
    }

    /**
     * Éditer un stage.
     * @Route("stage/{slug}/edit", name="stage.edit") * @param Request $request
     * @param Request $request
     * @param Stage $stage
     * @param EntityManagerInterface $em
     * @return RedirectResponse|Response
     */
    public function edit(Request $request, Stage $stage, EntityManagerInterface $em) : Response
    {
        $form = $this->createForm(StageType::class, $stage); $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em->flush();
            return $this->redirectToRoute('stage.list');
        }

        return $this->render('stage/create.html.twig', [
            'form' => $form->createView(),
            'editMode' => $stage->getId() !== null,
            ]);
    }


    /**
     * Supprimer un stage.
     * @Route("stage/{slug}/delete", name="stage.delete") * @param Request $request
     * @param Request $request
     * @param Stage $stage
     * @param EntityManagerInterface $em
     * @return Response
     */
    public function delete(Request $request, Stage $stage, EntityManagerInterface $em) : Response
    {
        $form = $this->createFormBuilder()
                     ->setAction($this->generateUrl('stage.delete', ['slug' => $stage->getSlug()]))
                     ->getForm();
        $form->handleRequest($request);

        if ( ! $form->isSubmitted() || ! $form->isValid()) {

            return $this->render('stage/delete.html.twig', [ 'stage' => $stage,
                'form' => $form->createView(),
            ]);
        }
        $em = $this->getDoctrine()->getManager(); $em->remove($stage);
        $em->flush();

        return $this->redirectToRoute('stage.list');
    }
}

GestionStages/templates/stage/create.html.twig
{% extends 'base.html.twig' %}

{% block body %}
        {{ form_start(form) }}

            <h1>Création d'annonce de stage :</h1>

            {{ form_row(form.poste, {'attr': {'placeholder': "Le poste de Stage" }}) }}
            {{ form_row(form.description, {'attr': {'placeholder': "La description du Stage"}}) }}
            {{ form_row(form.type) }}
            {{ form_row(form.actif) }}
            {{ form_row(form.email, {'attr': {'placeholder': "L'adresse email du responsable" }}) }}
            {{ form_row(form.societe, {'attr': {'placeholder': "Le nom de la societe"}}) }}
            {{ form_row(form.ville, {'attr': {'placeholder': "Le nom de la ville" }}) }}
            {{ form_row(form.categorie) }}
            {{ form_row(form.tuteurs) }}

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-success">
                        {% if editMode %}
                            {{ 'addIntership'|trans }}
                        {% else %}
                            Ajouter le stage
                            {{ 'editIntership'|trans }}
                        {% endif %}
                    </button>
                </div>
            </div>
        {{ form_end(form) }}
{% endblock %}

GestionStages/templates/stage/delete.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="alert alert-danger">
        <strong>Avertissement !</strong> Vous êtes en train de supprimer le stage suivant :
        <ul>
            <li><strong>Poste : </strong> {{ stage.poste }}</li>
            <li><strong>Societe : </strong>{{ stage.societe }}</li>
            <li><strong>Ville : </strong>{{ stage.ville }}</li>
            <li><strong>Description : </strong>{{ stage.description }}</li>
            <li><strong>Date de publication : </strong>{{ stage.dateCreation|date('m/d/Y') }}</li>
        </ul>
    </div>
    <div class="collapse navbar-collapse">
        {{ form_start(form, {'attr': {'class': 'navbar-form navbar-left'}}) }}
        {{ form_widget(form) }}
        <a href="{{ path('stage.list') }}" class="btn btn-success" role="button"><span class="glyphicon glyphicon-off" aria-hidden="true"></span>Annuler</a>
        <button type="submit" class="btn btn-danger" onclick="return confirm('Êtes vous sûr ??')">
            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
            Supprimer
        </button>
        {{ form_end(form) }}
    </div>
{% endblock %}

GestionStages/templates/stage/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello StageController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/Users/thiernoamiroudiallo/Desktop/Bureau - MacBook Pro de Thierno/Semestre6/Dev/GestionStages/src/Controller/StageController.php'|file_link(0) }}">src/Controller/StageController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/Users/thiernoamiroudiallo/Desktop/Bureau - MacBook Pro de Thierno/Semestre6/Dev/GestionStages/templates/stage/index.html.twig'|file_link(0) }}">templates/stage/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

GestionStages/templates/stage/list.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <table class="table text-center">
        <tr>
            <td>{{ 'history'|trans }} :
                {% for stageHistory in historyStages %}
                <a href="{{ path('stage.show', {slug: stageHistory.slug}) }}">
                        {{ stageHistory.poste }},
                </a>
                {% endfor%}
                <hr>
            </td>
        </tr>
    </table>
    <table class="table text-center">
        <tr>
            <th class="active text-center">{{ 'post'|trans }}</th>
            <th class="active text-center">{{ 'company'|trans }}</th>
            <th class="active text-center">{{ 'category'|trans}}</th>
            <th class="active text-center">{{ 'town'|trans }}</th>
            <th class="active text-center">{{ 'edition'|trans }}</th>
            <th class="active text-center">{{ 'deletion'|trans }}</th>
        </tr>

        {% for stage in stages %}
            <tr>
                <td><a href="{{ path('stage.show', {slug: stage.slug}) }}">{{ stage.poste }}</a></td>
                <td>
                    <a href="#">
                        {{ stage.societe }}
                    </a>
                </td>
                <td>{{ stage.categorie.nom }}</td>
                <td>{{ stage.ville }}</td>
                <td>
                    <a href="{{ path('stage.edit', {slug: stage.slug}) }}">
                        <button type="submit" class="btn btn-primary">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                            {{ 'edit'|trans }}
                        </button>
                    </a>
                </td>
                <td>
                    <a href="{{ path('stage.delete', {slug: stage.slug}) }}">
                        <button type="submit" class="btn btn-danger" onclick="return confirm('Êtes vous sûr ??')">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                            {{ 'delete'|trans }}
                        </button>
                    </a>
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

GestionStages/templates/stage/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Détails du stage <i>{{ stage.poste }}</i> à pourvoir :</h1>
    <div class="media" style="margin-top: 60px;">
        <div class="media-body">
            <div class="row">
                <div class="col-sm-10">
                    <h3 class="media-heading"><strong>{{ stage.societe }}</strong> <i>({{ stage.ville }})</i></h3>
                </div>

                <div class="col-sm-2">
                    <i class="pull-right">Publié le {{ stage.dateCreation|date('m/d/Y') }}</i>
                </div>
            </div>

            <p>
                <strong>{{ stage.poste }}</strong>
                <small> - <i>{{ stage.type }}</i></small>
            </p>

            <p>{{ stage.description|nl2br }}</p>

            <p>
                <strong>Email de contact :</strong> {{ stage.email }}
            </p>
            <p>
                <strong>Date d'expirtaion :</strong> {{ stage.dateExpiration|date('m/d/Y') }}
            </p>
            <p>
                <strong>Les tuteurs du stage : </strong>
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Nom</th>
                                <th>Prénom</th>
                                <th>Email</th>
                                <th>Téléphone</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for tuteur in stage.tuteurs %}
                                <tr>
                                    <td><a href="#">{{ tuteur.nom }}</a></td>
                                    <td>{{ tuteur.prenom }}</td>
                                    <td>{{ tuteur.email }}</td>
                                    <td>{{ tuteur.telephone }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
            </p>
            <div class="row">
                <div class="col-sm-12 text-right">
                    <a class="btn btn-default" href="#">
                        <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>
                        Liste des stages
                    </a>

                    <a class="btn btn-primary" href="{{ path('stage.edit', {slug: stage.slug}) }}">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                        Éditer
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}